import { User, Project } from './types'

export const mockUsers: User[] = [
  { id: 'u1', name: 'Jake Morrison', email: 'jake@lightco.com', role: 'sales', initials: 'JM' },
  { id: 'u2', name: 'Sarah Chen', email: 'sarah@lightco.com', role: 'sales', initials: 'SC' },
  { id: 'u3', name: 'Robert Kim', email: 'robert@lightco.com', role: 'admin', initials: 'RK' },
  { id: 'u4', name: 'System Admin', email: 'admin@lightco.com', role: 'super_admin', initials: 'SA' },
]

export const initialProjects: Project[] = [
  {
    id: 'p1',
    company: { id: 'c1', name: 'Maple Grove Foods Inc.', email: 'ops@maplegrovefoods.ca' },
    contacts: [
      {
        id: 'ct1', salutation: 'Mr.', fullName: 'David Maple',
        phone: '416-555-0101', address: '450 Maple St, Toronto, ON M5V 2H1',
        designation: 'Facility Manager',
      },
      {
        id: 'ct2', salutation: 'Ms.', fullName: 'Linda Chen',
        phone: '416-555-0102', address: '450 Maple St, Toronto, ON M5V 2H1',
        designation: 'CEO',
      },
    ],
    facility: { id: 'f1', name: 'Main Warehouse & Processing', electricityAccountNumber: 'ACC-ON-2024-001' },
    lightingFixtures: [
      { id: 'lf1', area: 'Warehouse Floor', fixtureType: 'Troffer Highbay', mountingType: 'Ceiling Mount', lampCount: 2, wattage: 400, voltage: 120, totalFixture: 24 },
      { id: 'lf2', area: 'Office Area', fixtureType: '4x2', mountingType: 'Recessed', lampCount: 4, wattage: 32, voltage: 120, totalFixture: 16 },
      { id: 'lf3', area: 'Parking Lot', fixtureType: 'Wallpack', mountingType: 'N/A', lampCount: 1, wattage: 175, voltage: 120, totalFixture: 8 },
      { id: 'lf4', area: 'Loading Dock', fixtureType: 'Metal Halide', mountingType: 'N/A', lampCount: 1, wattage: 250, voltage: 120, totalFixture: 6 },
    ],
    status: 'Validated',
    salesNotes: 'Client very interested. Key decision maker is Linda Chen. They have high hydro bills.',
    managementNotes: 'Strong candidate for SaveOnEnergy subsidy. Good fixture count for ROI.',
    followUpNotes: 'Follow-up call scheduled for May 10th regarding proposal.',
    subsidyAmount: 15000,
    subsidyProposalNumber: 'PROP-2024-0012',
    subsidyPspxNumber: 'PSPX-2024-0047',
    assignedSalesId: 'u1',
    reviewComments: '',
    documents: [
      { id: 'd1', name: 'Site Photos - Warehouse.zip', type: 'site_image', url: '#', uploadedAt: '2026-04-20T10:00:00Z', uploadedBy: 'Jake Morrison', size: '8.2 MB' },
    ],
    createdAt: '2026-04-15T09:00:00Z',
    updatedAt: '2026-04-28T14:00:00Z',
  },
  {
    id: 'p2',
    company: { id: 'c2', name: 'Riverside Auto Group', email: 'admin@riversideauto.ca' },
    contacts: [
      {
        id: 'ct3', salutation: 'Mr.', fullName: 'Tom Rivers',
        phone: '905-555-0201', address: '1200 Riverside Dr, Mississauga, ON L5G 4L3',
        designation: 'Operations Director',
      },
    ],
    facility: { id: 'f2', name: 'Main Dealership', electricityAccountNumber: 'ACC-ON-2024-089' },
    lightingFixtures: [
      { id: 'lf5', area: 'Showroom', fixtureType: '2x2', mountingType: 'Recessed', lampCount: 4, wattage: 32, voltage: 120, totalFixture: 40 },
      { id: 'lf6', area: 'Service Bay', fixtureType: 'Linear 8ft', mountingType: 'Ceiling Mount', lampCount: 2, wattage: 96, voltage: 120, totalFixture: 18 },
      { id: 'lf7', area: 'Canopy (Exterior)', fixtureType: 'Canopy', mountingType: 'N/A', lampCount: 1, wattage: 150, voltage: 120, totalFixture: 12 },
    ],
    status: 'Submitted',
    salesNotes: 'Tom is very cost-conscious. Emphasize 5-year payback.',
    managementNotes: '',
    followUpNotes: '',
    subsidyAmount: undefined,
    subsidyProposalNumber: undefined,
    subsidyPspxNumber: undefined,
    assignedSalesId: 'u1',
    reviewComments: '',
    documents: [],
    createdAt: '2026-04-22T11:00:00Z',
    updatedAt: '2026-04-29T09:00:00Z',
  },
  {
    id: 'p3',
    company: { id: 'c3', name: 'Northview Community Centre', email: 'manager@northviewcc.org' },
    contacts: [
      {
        id: 'ct4', salutation: 'Ms.', fullName: 'Patricia North',
        phone: '647-555-0301', address: '88 Northview Blvd, North York, ON M3B 1H2',
        designation: 'General Manager',
      },
    ],
    facility: { id: 'f3', name: 'Recreation Facility', electricityAccountNumber: 'ACC-ON-2024-123' },
    lightingFixtures: [
      { id: 'lf8', area: 'Gymnasium', fixtureType: 'Troffer Highbay', mountingType: 'Ceiling Mount', lampCount: 2, wattage: 320, voltage: 347, totalFixture: 20 },
      { id: 'lf9', area: 'Lobby', fixtureType: 'Potlights 6"', mountingType: 'Recessed', lampCount: 1, wattage: 65, voltage: 120, totalFixture: 30 },
    ],
    status: 'Rework Required',
    salesNotes: 'Patricia wants LED upgrade before winter.',
    managementNotes: '',
    followUpNotes: '',
    assignedSalesId: 'u2',
    reviewComments: 'Missing wattage data for gymnasium fixtures. Please re-verify voltage — 347V needs confirmation. Blurry image for lobby potlights.',
    documents: [],
    createdAt: '2026-04-25T14:00:00Z',
    updatedAt: '2026-04-30T16:00:00Z',
  },
  {
    id: 'p4',
    company: { id: 'c4', name: 'GreenTech Manufacturing', email: 'facilities@greentech.ca' },
    contacts: [
      {
        id: 'ct5', salutation: 'Dr.', fullName: 'Angela Green',
        phone: '905-555-0401', address: '500 Industrial Pkwy, Brampton, ON L6T 4H2',
        designation: 'VP Operations',
      },
    ],
    facility: { id: 'f4', name: 'Plant A - Assembly', electricityAccountNumber: 'ACC-ON-2024-202' },
    lightingFixtures: [],
    status: 'Draft',
    salesNotes: 'Just met at trade show. Very promising lead.',
    managementNotes: '',
    followUpNotes: '',
    assignedSalesId: 'u2',
    reviewComments: '',
    documents: [],
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'p5',
    company: { id: 'c5', name: 'Lakeside Hotel & Spa', email: 'gm@lakesidehotel.ca' },
    contacts: [
      {
        id: 'ct6', salutation: 'Mr.', fullName: 'James Lake',
        phone: '705-555-0501', address: '1 Lakeside Drive, Barrie, ON L4N 7T3',
        designation: 'General Manager',
      },
      {
        id: 'ct7', salutation: 'Mrs.', fullName: 'Claire Waters',
        phone: '705-555-0502', address: '1 Lakeside Drive, Barrie, ON L4N 7T3',
        designation: 'Facility Coordinator',
      },
    ],
    facility: { id: 'f5', name: 'Main Hotel Building', electricityAccountNumber: 'ACC-ON-2024-388' },
    lightingFixtures: [
      { id: 'lf10', area: 'Lobby & Reception', fixtureType: 'Potlights 4"', mountingType: 'Recessed', lampCount: 1, wattage: 65, voltage: 120, totalFixture: 48 },
      { id: 'lf11', area: 'Guest Rooms (per room)', fixtureType: 'Potlights 4"', mountingType: 'Recessed', lampCount: 1, wattage: 65, voltage: 120, totalFixture: 160 },
      { id: 'lf12', area: 'Parking Structure', fixtureType: 'Wallpack', mountingType: 'N/A', lampCount: 1, wattage: 175, voltage: 120, totalFixture: 30 },
      { id: 'lf13', area: 'Exterior Grounds', fixtureType: 'Post Top', mountingType: 'N/A', lampCount: 1, wattage: 150, voltage: 120, totalFixture: 20 },
    ],
    status: 'Quotation Generated',
    salesNotes: 'James very interested. Claire handles scheduling for site access.',
    managementNotes: 'High fixture count. Excellent subsidy opportunity under LDC program.',
    followUpNotes: 'Proposal emailed on April 30. Awaiting board approval.',
    subsidyAmount: 28500,
    subsidyProposalNumber: 'PROP-2024-0009',
    subsidyPspxNumber: 'PSPX-2024-0031',
    assignedSalesId: 'u1',
    reviewComments: '',
    documents: [
      { id: 'd2', name: 'Quotation_LakesideHotel_v1.pdf', type: 'quotation', url: '#', uploadedAt: '2026-04-30T09:00:00Z', uploadedBy: 'Robert Kim', size: '1.2 MB' },
      { id: 'd3', name: 'Subsidy_Proposal_PROP-2024-0009.pdf', type: 'proposal', url: '#', uploadedAt: '2026-04-30T09:15:00Z', uploadedBy: 'Robert Kim', size: '2.8 MB' },
    ],
    createdAt: '2026-04-10T08:00:00Z',
    updatedAt: '2026-04-30T09:15:00Z',
  },
  {
    id: 'p6',
    company: { id: 'c6', name: 'Pioneer Logistics Ltd.', email: 'ops@pioneerlogistics.ca' },
    contacts: [
      {
        id: 'ct8', salutation: 'Mr.', fullName: 'Mark Pioneer',
        phone: '416-555-0601', address: '2200 Airport Rd, Mississauga, ON L4V 1E1',
        designation: 'COO',
      },
    ],
    facility: { id: 'f6', name: 'Distribution Centre East', electricityAccountNumber: 'ACC-ON-2024-501' },
    lightingFixtures: [
      { id: 'lf14', area: 'Shipping Floor', fixtureType: 'Troffer Highbay', mountingType: 'Ceiling Mount', lampCount: 2, wattage: 400, voltage: 120, totalFixture: 60 },
      { id: 'lf15', area: 'Loading Bays', fixtureType: 'Metal Halide', mountingType: 'N/A', lampCount: 1, wattage: 250, voltage: 120, totalFixture: 20 },
      { id: 'lf16', area: 'Office', fixtureType: '4x2', mountingType: 'Recessed', lampCount: 4, wattage: 32, voltage: 120, totalFixture: 24 },
    ],
    status: 'Closed Won',
    salesNotes: 'Deal closed! Installation scheduled for June 2026.',
    managementNotes: 'Excellent client. Refer to other Pioneer facilities.',
    followUpNotes: 'Installation kick-off meeting set for June 3rd.',
    subsidyAmount: 42000,
    subsidyProposalNumber: 'PROP-2024-0003',
    subsidyPspxNumber: 'PSPX-2024-0011',
    assignedSalesId: 'u2',
    reviewComments: '',
    documents: [
      { id: 'd4', name: 'SignedContract_Pioneer.pdf', type: 'proposal', url: '#', uploadedAt: '2026-04-25T14:00:00Z', uploadedBy: 'Robert Kim', size: '3.4 MB' },
    ],
    createdAt: '2026-03-20T09:00:00Z',
    updatedAt: '2026-04-25T14:00:00Z',
  },
]
